# Generated by Django 5.0.6 on 2024-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticsrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsrecord',
            name='record_type',
            field=models.CharField(default='appointment', max_length=50),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
