# Generated by Django 5.0.6 on 2024-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('invoiced', 'invoiced'), ('due', 'due')], max_length=20),
        ),
    ]
