# Generated by Django 5.0.6 on 2024-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('invoiced', 'Invoiced'), ('due', 'Due')], max_length=20),
        ),
    ]
